include:
  - project: sysadmin/ci-utilities
    file: /gitlab-templates/blocks/workflow.yml

apidocs_website:
  image: storage.kde.org/vm-images/suse-qt610
  tags:
    - VM
    - amd64
  stage: build
  variables:
    LANG: en_US.UTF-8
    KDECI_PLATFORM_PATH: suse-qt6.11
    KDECI_CACHE_PATH: /mnt/$KDECI_PLATFORM_PATH/artifacts/
    KDECI_CC_CACHE: /mnt/$KDECI_PLATFORM_PATH/caches/
    KDECI_GITLAB_SERVER: https://invent.kde.org/
    KDECI_PACKAGE_PROJECT: teams/ci-artifacts/$KDECI_PLATFORM_PATH
    # Show timestamps in our job logs
    FF_TIMESTAMPS: true

  script:
    - rm -rf /mnt/*
